### ISSUE TITLE
`as_env` should return `frame$env` or `child_env` should understand `frame` objects

### ISSUE THREAD

**Issue by vspinu** [tidyverse/rlang#370] opened 2018-01-18 21:52 UTC
I used `call_frame` as an argument to `child_env` and incurred an obscure lookup error. It turned out that `as_env` within `child_env` creates new environment from frame objects.  I don't think this is an expected behavior for most people. 

I think  `child_env` should understand `frames`. Also `as_env` should probably return the `env` element of a frame. It's highly unlikely that someone would need to assign elements of a frame into environments. If ever needed one could simply do `as_env(unclass(frame))`.

```R
> tt <- function() {
+     cf <- call_frame(2)
+     stopifnot(identical(cf$env, as_env(cf)))
+ }
> tt()
Error: identical(cf$env, as_env(cf)) is not TRUE
> 
> tt <- function() {
+     cf <- call_frame(2)
+     child_env(cf, a = 1)
+ }
> env_parents(tt())
[[1]]
<environment: 0x633cd58>

[[2]]
<environment: R_EmptyEnv>

```

(this is rlang@master)

**Comment by lionel-** [comment] 2018-01-19 07:50
We're going to deprecate the frame and stack stuff, it's in questioning stage right now. Probably belongs to another package. We no longer want to make frames a first class citizen of rlang because they complicate implementations and encourage code based on call stack introspection. These are remnants of early stages of rlang when we were trying to reproduce lazyeval semantics with call stack information.

**Comment by vspinu** [comment] 2018-01-19 12:02
FWIW, I see rlang as a swiss knife of language programming. IMO, not having call stacks manipulation/introspection here would create a hole.  Plus, this endless fragmentation into separate packages is taking its toll on the end users :(

I agree that frame as first class is indeed not needed, but, getting the caller or lexical environment of a function is damn useful.

**Comment by lionel-** [comment] 2018-01-19 18:53
I see it more as a programming API than as an all-purpose library, which means that the stuff for interacting with the REPL does not belong to it. We're still figuring it out though. `caller_env()`, `caller_fn()` and co will remain in rlang for sure by the way.

**Comment by vspinu** [comment] 2018-01-19 22:07
BTW, there is no equivalent of `sys.call`?  `caller_call`? No match.call either?

**Comment by lionel-** [comment] 2018-01-20 06:14
We may add it in the future but in general we are trying not to encourage fexpr idioms based on `match.call()`.

**Comment by lionel-** [comment] 2018-01-21 16:23
Closing as this is about a part of the API that we are questioning.

**Closed by lionel-** 2018-01-21 16:23 UTC
