### ISSUE TITLE
exprs(foo = ) returns empty list

### ISSUE THREAD

**Issue by lionel-** [tidyverse/rlang#240] opened 2017-08-23 13:29 UTC

**Comment by lionel-** [comment] 2017-08-24 09:18
It's ignored because it's an empty trailing argument.

@hadley It seems that if an empty argument was supplied with a name, we shouldn't treat it as empty. Does that make sense? That won't affect common cases like `mutate(df, foo, )`

**Comment by hadley** [comment] 2017-08-24 12:49
Agreed.

**Comment by hadley** [comment] 2017-11-13 18:32
Duplicate of #286

**Closed** 2017-11-14 17:26 UTC
Labels: tidyeval
